# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


server:
  port: 8181

spring:
  application:
    name: retailstore
    main:
      allow-bean-definition-overriding: true # Whether bean definition overriding, by registering a definition with the same name as an existing definition, is allowed.
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:retail_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none #otherwise scripts will be ignored by hibernate,
                     # and it will scan project for @Entity and/or @Table annotated classes

# H2 Web Console (H2ConsoleProperties)
  h2:
    console:
      enabled: true
      path: /db-console
    implicitRelativePath: true

# LIQUIBASE (LiquibaseProperties)
  liquibase:
    change-log : classpath:db/changelog-master.xml # Change log configuration path.
    check-change-log-location: true # Whether to check that the change log location exists.
    database-change-log-lock-table: DATABASECHANGELOGLOCK # Name of table to use for tracking concurrent Liquibase usage.
    database-change-log-table: DATABASECHANGELOG # Name of table to use for tracking change history.

security:
  basic:
    enabled: false


# Logging
logging:
 level:
   com:
     retail: TRACE

